version: "3.9"

services:
  postgres:
    image: postgres:16.2-bookworm
    ports:
      - 5432:5432
    volumes:
      - tennis_school_management_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=tennis_school_management_db

volumes:
  tennis_school_management_data:
